[package]
name = "qool"
version = "0.0.1"
description = "A command line tool to generate QR code."
authors = ["watcol <kantaa058@gmail.com>"]
repository = "https://github.com/watcol/qool"
keywords = ["qr", "qrcode"]
categories = ["encoding", "command-line-utilities"]
license = "MIT"
readme = "README.md"
edition = "2018"

include = [
  "README.md",
  "Cargo.toml",
  "src/**/*.rs"
]

[dependencies]
qrcode = "0.12.0"
clap = "3.0.0-beta"
colored = "2.0"
selog = { version = "0.1.1-beta", features = ["opts"] }
log = "0.4.11"
atty = "0.2.14"
clipboard = "0.5.0"

[dependencies.image]
version = "0.23.11"
default_features = false
features = ["png", "jpeg", "gif", "bmp", "ico"]
